### ISSUE TITLE
Feature Request: Provide SHA algorithm selection

### ISSUE THREAD

**Issue by peteeveleigh** [welford-media/craft3-barclays-epdq#2]
ePDQ can use either sha1, sha256, or sha512 for its encryption algorithm. 

The plugin currently fixes that selection as sha1 - the least secure of the three options. And also provides no indication of doing so. This means that submissions fail if the ePDQ installation is set to use anything other than sha1.

Could you provide a setting to allow for selection of any of the 3 sha methods and adapt the calculate sha method in the plugin to use the appropriate one?

**Comment by timjai** [comment]
We've had the same issue so I've created a pull request for this.

**Comment by peteeveleigh** [comment]
@timjai fantastic. I already modified the plugin once but forgot I'd done it and overwrote my change with a reinstallation.
Was trying to make the time to do it again.
