### ISSUE TITLE
Locked dependency preventing updates

### ISSUE THREAD

**Issue by peteeveleigh** [welford-media/craft3-barclays-epdq#4]
Hi

The plugin is locked to craftcms/commerce-omnipay ^2.0.0 
This is causing an issue when trying to keep other gateways up to date as they are using Omnipay 3.

Would it be possible to update this dependency please?

**Comment by phillmorgan28** [comment]
Hi

My apologies for the delay. This has been added in v1.0.3 for you.

Kind regards,
