### ISSUE TITLE
Commerce 4 compatibility

### ISSUE THREAD

**Issue by johnwbaxter** [welford-media/craft3-barclays-epdq#5]
Will this be updated to work with Craft Commerce 4?

**Comment by phillmorgan28** [comment]
Hi

Please contact hello@welfordmedia.co.uk for information on future updates.

Thanks

**Comment by jamiematrix** [comment]
I've emailed asking the same question

**Comment by phillmorgan28** [comment]
> I've emailed asking the same question

Hi, if you check the 2.0.0 tag you can see that Commerce 4 is already supported
https://github.com/welford-media/craft3-barclays-epdq/tree/2.0.0

Thanks!

**Comment by jamiematrix** [comment]
Thanks for the link and info.

Is it possible to update the Craft Plugin Store with the different links? The current documentation and repo links come to this branch - at least 2 of us didn't think to check if there's another branch with Commerce 4 support.
