### ISSUE TITLE
Error after payment is authorised

### ISSUE THREAD

**Issue by jamiematrix** [welford-media/craft3-barclays-epdq#6]
I'm making some test payments to make sure all is well and I'm getting an error after the payment is authorised on Barclaycards side.

The error is
```
 PHP Compile Error – yii\base\ErrorException
Declaration of welfordmedia\barclaysepdqgateway\omni\Message\CompletePurchaseRequest::sendData($data): welfordmedia\barclaysepdqgateway\omni\Message\CompletePurchaseResponse must be compatible with welfordmedia\barclaysepdqgateway\omni\Message\PurchaseRequest::sendData($data): welfordmedia\barclaysepdqgateway\omni\Message\PurchaseResponse
```

Here is the stacktrace:
![image](https://github.com/welford-media/craft3-barclays-epdq/assets/58532601/f57a2776-955d-461e-9ad0-35671f5c7385)
... that is all there is.

As far as I can tell everything is setup for the gateway and Barclaycard account.

**Comment by phillmorgan28** [comment]
Hi

Can you tell me what PHP version you're using?

Thanks

**Comment by jamiematrix** [comment]
Hi,
The above error was using PHP 8.1

Thanks

**Comment by jamiematrix** [comment]
We've had a go troubleshooting ourselves and got a little further (at least past the error above).

Changing the following in `PurchasRequest.php` got a little further:
```
    public function sendData($data): CompletePurchaseResponse
    {
        $this->response = new CompletePurchaseResponse($this, $data);
        return $this->response->getData();
    }
```

**Comment by jamiematrix** [comment]
Is there any update to this issue @phillmorgan28 ?

**Comment by phillmorgan28** [comment]
Return types have been removed from 2.0.1 which solves the error you've been experiencing.
